### PR TITLE
add documentation for v1.1 routes

### PR DESCRIPTION
**Pull request by jacobsmith**
This adds in documentation for the new v1.1 routes.

The easiest way to preview it is to fetch this branch and run `bundle exec middleman` - that should open a server on `localhost:4567` where you can view the documentation in its normal Slate environment.

https://app.clubhouse.io/lessonly/story/3457/document-api-v1-1

### CODE REVIEW

**Comment by rreinhardt9** [comment]
@jacobsmith looks like this needs an update to "lessonly.com"

**Comment by jacobsmith** [comment]
Haha, thanks @baldwindavid and @rreinhardt9  -- I think I originally was working off of an old master and ran into issues with merging. Anyway, they should all be fixed up now! I ran `ack "lesson.ly"` and found nothing in the directory, so that's a good sign (:

**Comment by baldwindavid** [comment]
Rock on. I deployed the changes to production. Thanks!

**Comment by jacobsmith** [comment]
awesome, thank you!

**Pull request merged**
